CREATE TABLE LOCACAO
(
	NR_LOCACAO INT NOT NULL PRIMARY KEY IDENTITY,
	ID_CLIENTE INT NOT NULL,
	PLACA VARCHAR(7) NOT NULL,
	CONSTRAINT [FK_LOCACAO_VEICULO] FOREIGN KEY (PLACA) REFERENCES VEICULO(PLACA),
	CONSTRAINT [FK_LOCACAO_CLIENTE] FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
)